CorsairGarage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

page/urls.py
from django.urls import path, include
from page.views import add_service, delete_detail, delete_spare, detail_service, list_repair_order, index, list_services, log_out, sign_in, get_client,get_moto, \
                       add_Mbike, dashboard, consulta_cliente, get_moto_rut, render_pdf_view, valve_service,view_bikes_client, list_client, list_motos

urlpatterns = [
    path('', index, name= "index"),
    path('sign-in/', sign_in, name= "sign-in"),
    path('log-out/', log_out, name= "log-out"),
    path('dashboard/', dashboard, name= "dashboard"),
    path('create-cliente/<str:rut2>', consulta_cliente, name= "create-cliente"), #funcionando
    path('valve-service/', valve_service, name= "valve-service"),
    path('add-service/', add_service, name= "add-service"),
    path('list-services/', list_services, name= "list-services"),
    path('list-client/', list_client, name= "list-client"),
    path('list-motos/', list_motos, name= "list-motos"),
    path('get_client/<str:rut>', get_client, name= "get_client"),
    path('get_moto/<str:patente>', get_moto, name= "get_moto"),
    path('get_moto_rut/<str:rut>', get_moto_rut, name= "get_moto_rut"),
    # path('create-client/<str:rut2>', create_client, name= "create-client"), borrar
    path('add-Mbike/<str:rut>', add_Mbike, name= "add-Mbike"),
    path('view-bikes-client/<str:rut>', view_bikes_client, name= "view-bikes-client"),
    path('list-repair-order/', list_repair_order, name= "list-repair-order"),
    path('detail-service/<str:rut>/<str:patente>/<int:ficha>', detail_service, name= "detail-service"),
    path('delete-detail/<str:id>/<str:rut>/<str:patente>/<int:ficha>', delete_detail, name= "delete-detail"),
    path('delete-spare/<str:id>/<str:rut>/<str:patente>/<int:ficha>', delete_spare, name= "delete-spare"),
    path('render_pdf_view/<str:rut>/<str:patente>/<int:ficha_id>/<int:desc>/<int:total>/<int:totalFinal>', render_pdf_view, name= "render_pdf_view"),
]

page/models.py
from django.db import models
from django.core.validators import MaxLengthValidator
from django.contrib.auth.models import User


unidad_medida = [
    ('km', 'Kilometros'),
    ('Millas', 'Millas'),
]

opcion_tipo_sv = [
    ('Mantencion', 'Mantención'),
    ('Ajuste', 'Ajuste'),
    ('Reemplazo', 'Reemplazo'),
    ('Reparacion', 'Reparación'), 
    ('Modificacion', 'Modificación'), 
    ('Revision', 'Revisión'), 
]

class HoraHombre(models.Model):
    nombre_hh = models.CharField(max_length=50)
    descripcion_hh= models.CharField(max_length=250, verbose_name="Descripción")
    precio_hh= models.PositiveIntegerField(verbose_name="Precio")
    
    def __str__(self):
        return self.nombre_hh + ' $' + str(self.precio_hh)
    
class Cliente(models.Model):
    usuario_cli = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Usuario", null=True)
    rut_cli = models.CharField(primary_key=True, max_length=12, verbose_name="Rut")
    nombre_cli = models.CharField(max_length=50, verbose_name="Nombre")
    apellido_cli = models.CharField(max_length= 100, verbose_name="Apellido")
    direccion_clie = models.CharField(max_length=250, verbose_name="Dirección")
    celular_cli = models.IntegerField(verbose_name="Número contacto")
    
    def __str__(self):
        return self.rut_cli
    
class Vehiculo(models.Model):
    rut_cli = models.ForeignKey(Cliente, on_delete=models.CASCADE, verbose_name="Rut Cliente")
    patente_vh= models.CharField(primary_key=True, max_length=7, verbose_name="Patente")
    marca_vh = models.CharField(max_length=50, verbose_name="Marca")
    modelo_vh = models.CharField(max_length=50, verbose_name="Modelo")
    cilindrada_vh = models.PositiveIntegerField( verbose_name="Cilindrada")
    kilometraje_vh = models.PositiveIntegerField( verbose_name="Kilometraje")
    mill_km_vh = models.CharField(max_length=50, verbose_name="Unidad de Medida", choices=unidad_medida, default='Kilometros')
    
    def __str__(self):
        return self.patente_vh
    
class Servicio(models.Model):
    id = models.CharField(primary_key=True, max_length=20)
    nombre_sv = models.CharField(max_length=50, verbose_name= "Nombre Servicio")
    desc_sv = models.TextField(verbose_name= "Descripción Servicio")
    hrs_240 = models.FloatField( verbose_name="Horas hasta 240 cc")
    hrs_500 = models.FloatField( verbose_name="Horas hasta 500 cc")
    hrs_800 = models.FloatField( verbose_name="Horas hasta 800 cc")
    hrs_810 = models.FloatField( verbose_name="Horas desde 810 cc")
    tipo_sv = models.CharField(max_length=250 ,verbose_name= "Tipo Servicio", choices=opcion_tipo_sv, default='Mantención')
    id_hh = models.ForeignKey(HoraHombre, verbose_name= "ID Hora Hombre", on_delete=models.CASCADE)
    
    def __str__(self):
        return self.id +' - '+ self.nombre_sv
    
class Ficha_ingreso(models.Model):
    patente_vh = models.ForeignKey(Vehiculo, on_delete=models.CASCADE, verbose_name="Patente")
    rut_cli = models.ForeignKey(Cliente, on_delete=models.CASCADE, verbose_name="Rut")
    fecha_ing_fi= models.DateField(auto_now_add=True, verbose_name="Fecha Ingreso")
    observaciones_fi= models.TextField(verbose_name="Observaciones")
    km_mill_fi = models.IntegerField(verbose_name="Kilometraje", default=0)
    mill_km_vh = models.CharField(max_length=50, verbose_name="Unidad de Medida", choices=unidad_medida, default='Kilometros')
    
    def __str__(self):
        return str(self.id) #type: ignore
    
class Detalle(models.Model):
    precio_servicio = models.IntegerField( verbose_name="Precio servicio")
    id_fi = models.ForeignKey(Ficha_ingreso, on_delete=models.CASCADE, verbose_name="Número de Ficha", null=True, blank=True)
    id_sv = models.ForeignKey(Servicio, on_delete=models.CASCADE, verbose_name="Número de servicio")
    
    def __str__(self):
        return str(self.id_fi)

class Insumos(models.Model):
    codigo_is_externo = models.CharField(max_length=150, verbose_name="Código externo", default="CXI-111111")
    nombre_is = models.CharField(max_length=50, verbose_name="Nombre Insumo")
    cantidad_is = models.PositiveIntegerField( verbose_name="Cantidad")
    precio_is_unitario = models.IntegerField( verbose_name="Precio unitario", default=1)
    precio_total = models.IntegerField(verbose_name="Precio", default=1)
    id_fi = models.ForeignKey(Ficha_ingreso, on_delete=models.CASCADE, verbose_name="Id Ficha")
    
    def __str__(self):
        return self.nombre_is

class Trabajador(models.Model):
    usuario_trab = models.ForeignKey(User, on_delete=models.CASCADE, null= True)
    rut_trab = models.CharField(primary_key=True, verbose_name="Rut", max_length=11)
    nombre_trab = models.CharField(max_length=50, verbose_name="Nombre")
    apellido_trab_pa = models.CharField(max_length= 100, verbose_name="Apellido Paterno")
    apellido_trab_ma = models.CharField(max_length= 100, verbose_name="Apellido Materno")
    celular_trab = models.IntegerField(verbose_name="Número Contacto")
    tipo_trab = models.CharField(max_length=250, verbose_name="Clasificación")
    
    def __str__(self):
        return  self.nombre_trab + ' ' + self.apellido_trab_pa + ' ' +self.rut_trab
    
class Orden_trabajo(models.Model):
    fecha_ing_ot = models.DateField(auto_now_add=True, verbose_name="Fecha Ingreso")
    fecha_fin_ot = models.DateField(auto_now=False, verbose_name="Fecha Finalización", null=True, blank=True)
    id_fi = models.ForeignKey(Ficha_ingreso, on_delete=models.CASCADE, verbose_name="Ficha Ingreso" )
    rut_trab = models.ForeignKey(Trabajador, on_delete=models.CASCADE, verbose_name="Trabajador")
    total_fi= models.PositiveIntegerField(verbose_name="Total", default=0)
    def __str__(self):
        return str(self.id_fi)
    

class Falla(models.Model):
    nombre_f = models.CharField(max_length=50, verbose_name="Nombre Falla")
    desc_f = models.CharField(max_length=250, verbose_name="Descripción Falla")
    hora_hh_f = models.IntegerField( verbose_name="Horas Hombre")
    id_ot = models.ForeignKey(Orden_trabajo, models.CASCADE, verbose_name="Orden Trabajo")
    
    def __str__(self):
        return self.nombre_f
    
    
    

    
    
    
    
        
    

page/templates/app/add-Mbike.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}

<div class="container">   
    <div class="row">  
        <div class="col-12 col-md-6 offset-md-3 mt-3 border rounded shadow p-3 mb-4">
            <h3 class="display-4 text-center">Ingreso de Vehículo</h3>
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}     
                <button type="submit" class="button btn btn-success">Registrar</button>
            </form>
            <br>
        </div>
    </div>
</div>
<!-- 
<script>
    jQuery(document).ready(function() {
        alert("Welcome")
        jQuery('#id_patente_vh').keyup(function() {
            $(this).val($(this).val().toUpperCase());
        });
    });
</script>  -->
{% endblock content %}

page/templates/app/add-service.html
{% extends 'layouts/base-dashboard.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        {% include "includes/sidebar.html" %}
        <div class="offcvXSmenu">
            {% include "includes/menu-xs.html" %}
        </div>
        <div class="col mt-2">
            <div class="row d-flex justify-content-center">
                <div class="container">   
                    <div class="row">  
                        <div class="col-12 col-md-6 offset-md-3 mt-3 border rounded shadow p-3 mb-4">
                            <h3 class="display-6 text-center">Agregar Servicio</h3>
                            <form action="" method="POST">
                                {% csrf_token %}
                                {% bootstrap_form form %}     
                                <button type="submit" class="btn btn-dark">Guardar</button>
                                <button type="submit" class="btn btn-info" name="continue">Nuevo Servicio</button>
                            </form>
                            <br>
                        </div>
                    </div>
                </div>
            </div> 
        </div>
    </div>
</div>  

{% endblock content %}

page/templates/app/create-client.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}

<div class="container">   
    <div class="row">  
        <div class="col-12 col-md-6 offset-md-3 mt-3 border rounded shadow p-3 mb-4">
            <h3 class="display-4 text-center">Ingreso de cliente</h3>
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}     
                <button type="submit" class="button btn btn-success">Registrar</button>
            </form>
            <br>
        </div>
    </div>
</div>

 
{% endblock content %}

page/templates/app/create-cliente.html
{% extends 'layouts/base-dashboard.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        {% include "includes/sidebar.html" %}
        <div class="col mt-2">
            <div class="row d-flex justify-content-center">
                <div class="container">   
                    <div class="row">  
                        <div class="col-12 col-md-6 offset-md-3 mt-3 border rounded shadow p-3 mb-4">
                            <h3 class="display-6 text-center">Ingreso de cliente</h3>
                            <form action="" method="POST">
                                {% csrf_token %}
                                {% bootstrap_form form %}     
                                <button type="submit" class="btn btn-success">Registrar</button>
                            </form>
                            <br>
                        </div>
                    </div>
                </div>
            </div> 
        </div>
    </div>
</div>  
<script>
    $(document).ready( function () {
        $('#id_rut_cli').attr({
            onkeypress : 'return isNumber(event)',
            oninput : "checkRut(this)",
            maxlength: "12"
        });
    } );   
</script>
<script src="{% static 'js/app/check.js'%}"></script>
{% endblock content %}

page/templates/app/dashboard.html
{% extends 'layouts/base-dashboard.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        
        {% include "includes/sidebar.html" %}
        <div class="offcvXSmenu">
            {% include "includes/menu-xs.html" %}
        </div>
        <div class="col mt-2 me-1">
            <div class="row d-flex justify-content-center">
                <div class="col-xl-4 col-lg-6 col-md-12">
                    <div class="card l-bg-cherry">
                        <div class="card-statistic-3 p-4">
                            <div class="card-icon card-icon-large"><i class="fas fa-shopping-cart"></i></div>
                            <div class="mb-4">
                                <h5 class="card-title mb-0">Ordenes de trabajo</h5>
                            </div>
                            <div class="row align-items-center mb-2 d-flex">
                                <div class="col-8">
                                    <h2 class="d-flex align-items-center mb-0">
                                        3,243
                                    </h2>
                                </div>
                                <div class="col-4 text-right">
                                    <span>12.5% <i class="fa fa-arrow-up"></i></span>
                                </div>
                            </div>
                            <div class="progress mt-1 " data-height="8" style="height: 8px;">
                                <div class="progress-bar l-bg-cyan" role="progressbar" data-width="25%"
                                    aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%;">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-4 col-lg-6 col-md-12">
                    <div class="card l-bg-blue-dark">
                        <div class="card-statistic-3 p-4">
                            <div class="card-icon card-icon-large"><i class="fas fa-users"></i></div>
                            <div class="mb-4">
                                <h5 class="card-title mb-0">Clientes</h5>
                            </div>
                            <div class="row align-items-center mb-2 d-flex">
                                <div class="col-8">
                                    <h2 class="d-flex align-items-center mb-0">
                                        15.07k
                                    </h2>
                                </div>
                                <div class="col-4 text-right">
                                    <span>9.23% <i class="fa fa-arrow-up"></i></span>
                                </div>
                            </div>
                            <div class="progress mt-1 " data-height="8" style="height: 8px;">
                                <div class="progress-bar l-bg-green" role="progressbar" data-width="25%"
                                    aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%;">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-4 col-lg-6 col-md-12">
                    <div class="card l-bg-green-dark">
                        <div class="card-statistic-3 p-4">
                            <div class="card-icon card-icon-large"><i class="fas fa-solid fa-motorcycle"></i></div>
                            <div class="mb-4">
                                <h5 class="card-title mb-0">Vehículos</h5>
                            </div>
                            <div class="row align-items-center mb-2 d-flex">
                                <div class="col-8">
                                    <h2 class="d-flex align-items-center mb-0">
                                        578
                                    </h2>
                                </div>
                                <div class="col-4 text-right">
                                    <span>10% <i class="fa fa-arrow-up"></i></span>
                                </div>
                            </div>
                            <div class="progress mt-1 " data-height="8" style="height: 8px;">
                                <div class="progress-bar l-bg-orange" role="progressbar" data-width="25%"
                                    aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%;">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row d-flex justify-content-evenly mt-2">
                    <div class="col-md-5 shadow rounded-4 l-bg-purple-dark">
                        <h4 class="text-center fs-5 mt-2">Consultar Cliente</h4>
                        <div class="form-floating mb-3 text-center text-dark">
                            <input type="text" class="form-control border" id="buscarCliente" placeholder=" " onkeypress = 'return isNumber(event)' oninput = "checkRut(this)" maxlength= "12">
                            <label for="buscarCliente">Rut Cliente</label>
                            <!-- <button class="btn btn-outline-light mt-2" type="submit"
                                name="btnConsultaCliente" id="ConsultarCli" onclick="captureInputrut(event)">Consultar</button> -->
                            <button class="btn btn-outline-light mt-2" type="submit" name="btnConsultaCliente"
                                onclick="captureInput(event)" id="ConsultarCli">consultar</button>
                        </div>
                    </div>
                    <div class="col-md-5 shadow rounded-4 l-bg-gray-dark mt-2">
                        <form action="" method="GET">
                            <h4 class="text-center fs-5 mt-2 ">Consultar Patente</h4>
                            <div class="form-floating mb-3 text-center text-dark">
                                <input type="text" class="form-control" id="buscarPatente" name="buscarPatente" placeholder=" ">
                                <label for="buscarPatente">Patente Vehículo</label>
                                <button class="btn btn-outline-dark text-light mt-2" type="submit" name="btnConsultaPatente"
                                    id="btnConsultarPatente">Consultar</button>
                            </div>
                        </form>

                    </div>
                </div>
                <div class="row mt-4"> <!-- reparar margen-->
                    <div class="col-12 shadow rounded-4">
                        <h4 class="text-center mt-2">Ordenes de Trabajo Activas</h4>
                        <div class="table-responsive">
                            <table class="table table-hover ">
                                <thead>
                                    <tr>
                                        <th scope="col">Patente</th>
                                        <th scope="col">Cliente</th>
                                        <th scope="col">Celular</th>
                                        <th scope="col">Fecha de ingreso</th>
                                        <th scope="col">Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td scope="row">1</td>
                                        <td>Mark</td>
                                        <td>Otto</td>
                                        <td>@mdo</td>
                                        <td>@mdo</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Modal -->
    <div class="modal fade" id="modalQuery" tabindex="-1" aria-labelledby="exampleModalLabel" data-bs-backdrop="static"
        data-bs-keyboard="false" aria-hidden="true">
        <div class="modal-dialog modal-notify modal-info">
            <div class="modal-content text-center" role="document">
                <div class="modal-header d-flex justify-content-center">
                    <h1 class="modal-title fs-5 text-center" id="exampleModalLabel">Alerta</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="textQuery">
                    {% comment %} puedo agregar un icono {% endcomment %}
                    <h5 id="modalText">El usuario consultado no esta registrado...</h5>
                </div>
                <div class="modal-footer" id="footerModal">
                    <button type="button" class="btn btn-secondary"><a href="{% url 'dashboard' %}">Cerrar</a></button>
                    <button type="button" class="btn btn-dark" onclick="registerQuery(event)" ><a
                            href="" id="btnRegister">Registrar</a></button>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
</div>

<script src="{% static 'js/app/check.js'%}"></script>
<script>
  
</script>
{% endblock content %}

page/templates/app/ficha-ingreso.html
{% extends 'layouts/base-dashboard.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        {% include "includes/sidebar.html" %}
        <div class="col mt-2">
            <div class="row d-flex justify-content-center">
                <div class="container">   
                    <div class="row">  
                        <div class="col-12 col-md-6 offset-md-3 mt-3 border rounded shadow p-3 mb-4">
                            <h3 class="display-6 text-center">Ficha Ingreso</h3>
                            <form action="" method="POST">
                                {% csrf_token %}
                                {% bootstrap_form form %}     
                                <button type="submit" class="btn btn-dark">Ingresar</button>
                            </form>
                            <br>
                        </div>
                    </div>
                </div>
            </div> 
        </div>
    </div>
</div>  

{% endblock content %}

page/templates/app/view-bikes-client.html
{% extends 'layouts/base-dashboard.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        {% include "includes/sidebar.html" %}
        <div class="col mt-2">
            <div class="row d-flex justify-content-center">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-md-6 offset-md-3 mt-3 border rounded-5 shadow p-4 mb-4">
                            <div class="text-center">
                                <h4>Motocicletas Registradas</h4>
                            </div>
                            <div class="fs-6">
                                <p>Nombre: {{client.nombre_cli}} {{client.apellido_cli}} </p>
                                <p>Rut: {{client.rut_cli}}</p>
                                <p>Contacto: {{client.celular_cli}}</p>
                            </div>
                            <div class="">
                                <a href="{% url 'add-Mbike' client.rut_cli  %}" class="btn btn-warning">Registrar nueva motocicleta</a>
                            </div>
                            <div class="table">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th scope="col">Patente</th>
                                            <th scope="col">Marca</th>
                                            <th scope="col">Modelo</th>
                                            <th scope="col">CC</th>
                                            <th scope="col">Accion</th>
                                        </tr>
                                    </thead>
                                    <tbody >
                                        {% for bike in Mbikes %}
                                        <tr>
                                            <td scope="row">{{bike.patente_vh}}</td>
                                            <td>{{bike.marca_vh}}</td>
                                            <td>{{bike.modelo_vh}}</td>
                                            <td>{{bike.cilindrada_vh}}</td>
                                            <td>
                                                <div class="btn-group">
                                                    <button type="button" class="btn btn-sm btn-dark"
                                                        data-arg1="{{bike.patente_vh}}" onclick="data(this)"
                                                        id="{{bike.patente_vh}}">Ingresar</button>
                                                    <button type="button"
                                                        class="btn btn-sm btn-danger dropdown-toggle dropdown-toggle-split"
                                                        data-bs-toggle="dropdown" aria-expanded="false">
                                                        <span class="visually-hidden">Toggle Dropdown</span>
                                                    </button>
                                                    <ul class="dropdown-menu">
                                                        <li>
                                                            <button type="button" class="dropdown-item btn btn-info"
                                                                data-arg2="{{bike.patente_vh}}"
                                                                onclick="viewHistory(this)">
                                                                Historial
                                                            </button>
                                                        </li>
                                                        <li><a class="dropdown-item" href="#">Eliminar</a></li>
                                                    </ul>
                                                </div>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="row" id="historyView">
                        <div class="col-12 col-md-6 offset-md-3 mt-1 border rounded-5 shadow p-3 mb-1">
                            <h6 class="text-center">Historial</h6>
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">ID ficha</th>
                                        <th scope="col">Patente</th>
                                        <th scope="col">Fecha Ingreso</th>
                                        <th scope="col">Handle</th>
                                    </tr>
                                </thead>
                                <tbody id="bodyTable">
                                    {% for fi in fi_client %}
                                    <tr>
                                        <th scope="row">{{fi.id}}</th>
                                        <td>{{fi.patente_vh}}</td>
                                        <td>{{fi.fecha_ing_fi}}</td>
                                        <td><a href="{% url 'detail-service' client.rut_cli fi.patente_vh fi.id %}"><i
                                                    class="fa-regular fa-eye btn btn-info"></i></a></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 col-md-6 offset-md-3 mt-3 border rounded-5 shadow p-3 mb-4">
                            <h3 class="display-6 text-center">Ficha Ingreso</h3>
                            <form action="" method="POST">
                                {% csrf_token %}
                                {% bootstrap_form form %}
                                <button type="submit" class="btn btn-dark">Ingresar</button>
                            </form>
                            <br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<script>
    $(document).ready(function () {
        $('#id_patente_vh').attr("style", "pointer-events: none;");
        $('#historyView').attr('style', "display: none;");
    });
    const data = (object) => {
        let patente = object.dataset.arg1;
        $('#id_patente_vh').val(patente).change();
    };
    const viewHistory = (object) => {
        let patente = object.dataset.arg2
        $('#historyView').attr('style', "display: block;");
        $('#bodyTable tr').filter(function () {
            $(this).toggle($(this).text().toUpperCase().indexOf(patente) > -1)
        });
    };
</script>

{% endblock content %}